{% set name = "geoh5py" %}
{% set version = "0.10.0" %}
{% set python_min = "3.10" %}
{% set python_max = "3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MiraGeoscience/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 17f3a262971d8eb639c8e2b510a8aac37b6f4fb8004ae14291e8ee18ecd5b248

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - setuptools
    - pip
  run:
    - python >={{ python_min }},<{{ python_max }}
    - h5py >=3.2.1,<4.0.0
    - numpy >=1.26,<1.27.0
    - pillow >=10.3.0,<10.4.0

test:
  imports:
    - geoh5py
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://www.mirageoscience.com/mining-industry-software/python-integration/
  summary: 'Python API for geoh5, an open file format for geoscientific data.'
  description: |
    The geoh5py library has been created for the manipulation and storage of a wide range of 
    geoscientific data (points, curve, surface, 2D and 3D grids) in GEOH5 file format. Users will 
    be able to directly leverage the powerful visualization capabilities of 
    (Geoscience ANALYST)<https://mirageoscience.com/mining-industry-software/geoscience-analyst/> 
    along with open-source code from the Python ecosystem.
  license: LGPL-3.0-only
  license_file:
    - COPYING
    - COPYING.LESSER
    - docs/THIRD_PARTY_SOFTWARE.rst
  doc_url: https://mirageoscience-geoh5py.readthedocs-hosted.com/
  dev_url: https://github.com/MiraGeoscience/geoh5py

extra:
  recipe-maintainers:
    - SophieCurinier
    - sebhmg
