schema_version: 1

context:
  name: geoh5py
  version: "0.11.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/MiraGeoscience/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: 847f6ece54c3e65bc45dc27cc3b0b0dcf5c1f78dea3d2fca55822a9a5b3d12fe

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry-core >=1.0.0
    - setuptools
  run:
    - python >=${{ python_min }}
    - h5py >=3.2.1, <4.0.dev
    - numpy >=1.26.0, <1.27.dev
    - pillow >=10.3.0, <10.4.dev
    - pydantic >=2.5.2, <3.0.dev

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - geoh5py
      pip_check: true
  - script:
      - pytest --ignore=tests/version_test.py
    requirements:
      run:
        - pytest
        - scipy >= 1.14.0, <1.15.dev
    files:
      source:
        - tests/

about:
  summary: Python API for geoh5, an open file format for geoscientific data.
  description: |
    The geoh5py library has been created for the manipulation and storage of a wide range of
    geoscientific data (points, curve, surface, 2D and 3D grids) in GEOH5 file format. Users will
    be able to directly leverage the powerful visualization capabilities of
    (Geoscience ANALYST)<https://mirageoscience.com/mining-industry-software/geoscience-analyst/>
    along with open-source code from the Python ecosystem.
  license: LGPL-3.0-only
  license_file:
    - COPYING
    - COPYING.LESSER
    - docs/THIRD_PARTY_SOFTWARE.rst
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration/
  repository: https://github.com/MiraGeoscience/geoh5py
  documentation: https://mirageoscience-geoh5py.readthedocs-hosted.com/

extra:
  recipe-maintainers:
    - andrewg-mira
    - sebhmg
